export const validEmail = 'teste@teste.com';
export const invalidEmail = 'teste.com';

export const validPassword = '1234567';
export const invalidPassword = '123456';

export const profileIconPath = 'profileIcon.svg';
export const searchIconPath = 'searchIcon.svg';

export const moreThanOneTypeCase = 'Your search must have only 1 (one) character';

export const errorMessage = 'Sorry, we haven\'t found any recipes for these filters.';

export const drinkByIngredient = {
  drinks: [
    {
      strDrink: 'Derby',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg',
      idDrink: '17187',
    },
    {
      strDrink: 'Frozen Mint Daiquiri',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jrhn1q1504884469.jpg',
      idDrink: '11390',
    },
    {
      strDrink: 'Mango Mojito',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/wfqmgm1630406820.jpg',
      idDrink: '178358',
    },
    {
      strDrink: 'Mint Julep',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/squyyq1439907312.jpg',
      idDrink: '17206',
    },
    {
      strDrink: 'Mojito Extra',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vwxrsw1478251483.jpg',
      idDrink: '15841',
    },
    {
      strDrink: 'Raspberry Julep',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hyztmx1598719265.jpg',
      idDrink: '178333',
    },
    {
      strDrink: 'Smashed Watermelon Margarita',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/dztcv51598717861.jpg',
      idDrink: '178332',
    },
  ],
};

export const singleCaseFoodData = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: 'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const searchedFoodData = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: 'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52797',
      strMeal: 'Spicy North African Potato Salad',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Moroccan',
      strInstructions: 'Cook potatoes - place potatoes in a pot of cold water, and bring to the boil. Boil 20 minutes, or until potatoes are tender. You know they are cooked when you can stick a knife in them and the knife goes straight through.\r\nCombine harissa spice, olive oil, salt and pepper and lemon juice in a small bowl and whisk until combined.\r\nOnce potatoes are cooked, drain water and roughly chop potatoes in half.\r\nAdd harissa mix and spring onions/green onions to potatoes and stir.\r\nIn a large salad bowl, lay out arugula/rocket.\r\nTop with potato mix and toss.\r\nAdd fetta, mint and sprinkle over pine nuts.\r\nAdjust salt and pepper to taste.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg',
      strTags: 'Vegetarian,Spicy',
      strYoutube: 'https://www.youtube.com/watch?v=zxBzwJvTK4g',
      strIngredient1: 'Small Potatoes',
      strIngredient2: 'Harissa Spice',
      strIngredient3: 'olive oil',
      strIngredient4: 'Lemon',
      strIngredient5: 'Spring onions',
      strIngredient6: 'Rocket',
      strIngredient7: 'Feta',
      strIngredient8: 'Mint',
      strIngredient9: 'Pine nuts',
      strIngredient10: 'Salt',
      strIngredient11: 'Pepper',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '650g/1lb 8 oz',
      strMeasure2: '1 tsp',
      strMeasure3: '2 tsp',
      strMeasure4: 'juice of half',
      strMeasure5: '4',
      strMeasure6: '150g/6oz',
      strMeasure7: '80g/3oz',
      strMeasure8: '20 chopped',
      strMeasure9: '2 tablespoons',
      strMeasure10: 'Pinch',
      strMeasure11: 'Pinch',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    }],
};

export const singleCaseDrinksData = {
  drinks: [
    {
      idDrink: '12754',
      strDrink: 'Sex on the Beach',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions: 'Build all ingredients in a highball glass filled with ice. Garnish with orange slice.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten in einem mit Eis gefüllten Highball-Glas geben. Mit einer Orangenscheibe garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti tutti gli ingredienti in un bicchiere highball pieno di ghiaccio. Guarnire con fetta d\'arancia.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/lijtw51551455287.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Peach schnapps',
      strIngredient3: 'Cranberry juice',
      strIngredient4: 'Grapefruit juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '3/4 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-21 10:12:45',
    }],
};

export const doneRecipesLS = [
  {
    id: '52929',
    type: 'food',
    nationality: 'Canadian',
    category: 'Dessert',
    alcoholicOrNot: '',
    name: 'Timbits',
    image: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
    doneDate: '31/8/2022',
    tags: [
      'Snack',
      'Treat',
    ],
  },
  {
    id: '12654',
    type: 'drink',
    nationality: '',
    category: 'Shake',
    alcoholicOrNot: 'Non alcoholic',
    name: 'Banana Milk Shake',
    image: 'https://www.thecocktaildb.com/images/media/drink/rtwwsx1472720307.jpg',
    doneDate: '1/9/2022',
    tags: [],
  },
];

export const timbitsFoodData = {
  meals: [
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: 'Sift together dry ingredients.\r\nMix together wet ingredients and incorporate into dry. Stir until smooth.\r\nDrop by teaspoonfuls(no bigger) into hot oil (365 degrees, no hotter), turning after a few moments until golden brown on all sides.\r\nRemove and drain.\r\nRoll in cinnamon sugar while still warm and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strTags: 'Snack,Treat',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Sugar',
      strIngredient3: 'Baking Powder',
      strIngredient4: 'Salt',
      strIngredient5: 'Egg',
      strIngredient6: 'Milk',
      strIngredient7: 'Oil',
      strIngredient8: 'Oil',
      strIngredient9: 'Icing Sugar',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1/3 cup',
      strMeasure3: '3 tsp',
      strMeasure4: '½ tsp',
      strMeasure5: '1 beaten',
      strMeasure6: '¾ cup',
      strMeasure7: '3 tbs',
      strMeasure8: 'for frying',
      strMeasure9: 'garnish',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const burekFoodData = {
  meals: [
    {
      idMeal: '53060',
      strMeal: 'Burek',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strInstructions: 'Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
      strTags: 'Streetfood, Onthego',
      strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
      strIngredient1: 'Filo Pastry',
      strIngredient2: 'Minced Beef',
      strIngredient3: 'Onion',
      strIngredient4: 'Oil',
      strIngredient5: 'Salt',
      strIngredient6: 'Pepper',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 Packet',
      strMeasure2: '150g',
      strMeasure3: '150g',
      strMeasure4: '40g',
      strMeasure5: 'Dash',
      strMeasure6: 'Dash',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const adamDrinkData = {
  drinks: [
    {
      idDrink: '17837',
      strDrink: 'Adam',
      strDrinkAlternate: null,
      strTags: 'Alcoholic,Holiday',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
      strInstructionsES: 'Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.',
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Lemon juice',
      strIngredient3: 'Grenadine',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:29:29',
    },
  ],
};

export const recipeInProgressAdam = {
  cocktails: {
    17837: [
      'Dark rum 2 oz ',
      'Lemon juice 1 oz ',
    ],
  },
};

export const recipeInProgressBurek = {
  meals: {
    53060: [
      'Filo Pastry 1 Packet',
      'Minced Beef 150g',
      'Onion 150g',
    ],
  },
};

export const doneRecipeBurek = [
  {
    id: '53060',
    type: 'food',
    nationality: 'Croatian',
    category: 'Side',
    alcoholicOrNot: '',
    name: 'Burek',
    image: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
    doneDate: '2/9/2022',
    tags: [
      'Streetfood',
      ' Onthego',
    ],
  },
];
