export const validEmail = 'teste@teste.com';
export const invalidEmail = 'teste.com';

export const validPassword = '1234567';
export const invalidPassword = '123456';

export const profileIconPath = 'profileIcon.svg';
export const searchIconPath = 'searchIcon.svg';

export const moreThanOneTypeCase = 'Your search must have only 1 (one) character';

export const singleCaseFoodData = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: 'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const searchedFoodData = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: 'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52797',
      strMeal: 'Spicy North African Potato Salad',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Moroccan',
      strInstructions: 'Cook potatoes - place potatoes in a pot of cold water, and bring to the boil. Boil 20 minutes, or until potatoes are tender. You know they are cooked when you can stick a knife in them and the knife goes straight through.\r\nCombine harissa spice, olive oil, salt and pepper and lemon juice in a small bowl and whisk until combined.\r\nOnce potatoes are cooked, drain water and roughly chop potatoes in half.\r\nAdd harissa mix and spring onions/green onions to potatoes and stir.\r\nIn a large salad bowl, lay out arugula/rocket.\r\nTop with potato mix and toss.\r\nAdd fetta, mint and sprinkle over pine nuts.\r\nAdjust salt and pepper to taste.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg',
      strTags: 'Vegetarian,Spicy',
      strYoutube: 'https://www.youtube.com/watch?v=zxBzwJvTK4g',
      strIngredient1: 'Small Potatoes',
      strIngredient2: 'Harissa Spice',
      strIngredient3: 'olive oil',
      strIngredient4: 'Lemon',
      strIngredient5: 'Spring onions',
      strIngredient6: 'Rocket',
      strIngredient7: 'Feta',
      strIngredient8: 'Mint',
      strIngredient9: 'Pine nuts',
      strIngredient10: 'Salt',
      strIngredient11: 'Pepper',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '650g/1lb 8 oz',
      strMeasure2: '1 tsp',
      strMeasure3: '2 tsp',
      strMeasure4: 'juice of half',
      strMeasure5: '4',
      strMeasure6: '150g/6oz',
      strMeasure7: '80g/3oz',
      strMeasure8: '20 chopped',
      strMeasure9: '2 tablespoons',
      strMeasure10: 'Pinch',
      strMeasure11: 'Pinch',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    }],
};

export const singleCaseDrinksData = {
  drinks: [
    {
      idDrink: '12754',
      strDrink: 'Sex on the Beach',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions: 'Build all ingredients in a highball glass filled with ice. Garnish with orange slice.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten in einem mit Eis gefüllten Highball-Glas geben. Mit einer Orangenscheibe garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti tutti gli ingredienti in un bicchiere highball pieno di ghiaccio. Guarnire con fetta d\'arancia.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/lijtw51551455287.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Peach schnapps',
      strIngredient3: 'Cranberry juice',
      strIngredient4: 'Grapefruit juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '3/4 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-21 10:12:45',
    }],
};

export const burekFoodData = {
  "meals": [
    {
      "idMeal": "53060",
      "strMeal": "Burek",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Croatian",
      "strInstructions": "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
      "strTags": "Streetfood, Onthego",
      "strYoutube": "https://www.youtube.com/watch?v=YsJXZwE5pdY",
      "strIngredient1": "Filo Pastry",
      "strIngredient2": "Minced Beef",
      "strIngredient3": "Onion",
      "strIngredient4": "Oil",
      "strIngredient5": "Salt",
      "strIngredient6": "Pepper",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 Packet",
      "strMeasure2": "150g",
      "strMeasure3": "150g",
      "strMeasure4": "40g",
      "strMeasure5": "Dash",
      "strMeasure6": "Dash",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};

export const adamDrinkData = {
  "drinks": [
    {
      "idDrink": "17837",
      "strDrink": "Adam",
      "strDrinkAlternate": null,
      "strTags": "Alcoholic,Holiday",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
      "strInstructionsES": "Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.",
      "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg",
      "strIngredient1": "Dark rum",
      "strIngredient2": "Lemon juice",
      "strIngredient3": "Grenadine",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 tsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2016-09-02 11:29:29"
    },
    {
      "idDrink": "16333",
      "strDrink": "Adam Bomb",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Punch / Party Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Margarita/Coupette glass",
      "strInstructions": "Add ice to blender (or to glass if prefer on the rocks) then fruit, and fruite juice depending on personal prefference then add the Rum, Vodka, Tequila, and triple sec. blend till smooth, rim glass with sugar or salt and pour mixture in. garnish with lemon or lime slice.",
      "strInstructionsES": "Agregue hielo a la licuadora (o al vaso, si lo prefiere). Agregue las frutas y el jugo de frutas según sus preferencias personales, después agregue el Ron, el Vodka, el Tequila y el Triple Dry. Bate hasta que quede homogeneo, decora el vaso con azúcar o sal en el borde y vierte la mezcla. Adorne con una rodaja de lima o limón.",
      "strInstructionsDE": "Eis in den Mixer (oder in ein Glas, wenn Sie lieber On the Rocks bevorzugen), dann Obst und Fruchtsaft je nach persönlicher Vorliebe, dann Rum, Wodka, Tequila und Triple Sec. zugeben, bis sie glattflächig sind, Glas mit Zucker oder Salz einrühren und die Mischung hineingeben. Mit Zitronen- oder Limonenscheibe garnieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Aggiungere il ghiaccio al frullatore (o al bicchiere se si preferisce con ghiaccio) poi la frutta e il succo di frutta a seconda delle preferenze personali, quindi aggiungere il rum, la vodka, la tequila e il triple sec.\r\nFrullare fino a che non diventa liscio, riempire l'orlo del bicchiere con zucchero o sale, e versare il composto.\r\nGuarnire con una fetta di limone o lime.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tpxurs1454513016.jpg",
      "strIngredient1": "Rum",
      "strIngredient2": "Vodka",
      "strIngredient3": "Tequila",
      "strIngredient4": "Triple sec",
      "strIngredient5": "Fruit",
      "strIngredient6": "Ice",
      "strIngredient7": "Salt",
      "strIngredient8": "Fruit juice",
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 part ",
      "strMeasure2": "1 part ",
      "strMeasure3": "1 part ",
      "strMeasure4": "1/2 part ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": "1-3 pint ",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-02-03 15:23:36"
    },
    {
      "idDrink": "17226",
      "strDrink": "Adam & Eve",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Shake together all the ingredients and strain into a cold glass.",
      "strInstructionsES": "Agitar todos los ingredientes y colarlos en un vaso enfriado.",
      "strInstructionsDE": "Alle Zutaten vermengen und in ein kaltes Glas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare insieme tutti gli ingredienti e filtrare in un bicchiere freddo.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Cognac",
      "strIngredient3": "Creme de Cassis",
      "strIngredient4": "Fresh Lemon Juice",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 shot ",
      "strMeasure2": "1 shot ",
      "strMeasure3": "1 shot ",
      "strMeasure4": "1/8 shot ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-07 22:17:58"
    },
    {
      "idDrink": "15567",
      "strDrink": "Adam Sunrise",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Collins Glass",
      "strInstructions": "Fill blender up with ice. Fill half with Bartons Vodka. Put 10 tsp of sugar, add 1/2 can lemonade concentrate, fill to top with water. Blend for 60 seconds.",
      "strInstructionsES": "Llena la licuadora con hielo. Llena hasta la mitad del vaso de la licuadora con Bartons Vodka. Agregue 10 cucharaditas de azúcar, agregue 1/2 botella de limonada Schweppes, llene hasta arriba con agua. Mezclar durante 60 segundos.",
      "strInstructionsDE": "Den Mixer mit Eis auffüllen. Füllen Sie die Hälfte mit Bartons Wodka. 10 Teelöffel Zucker hinzufügen, 1/2 Dose Limonadenkonzentrat hinzufügen, mit Wasser füllen. 60 Sekunden lang mischen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Riempi il frullatore di ghiaccio.\r\nRiempi metà con Bartons Vodka.\r\nMettere 10 cucchiaini di zucchero, aggiungere 1/2 lattina di concentrato di limonata, riempire con acqua.\r\nFrulla per 60 secondi.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vtuyvu1472812112.jpg",
      "strIngredient1": "Vodka",
      "strIngredient2": "Lemonade",
      "strIngredient3": "Water",
      "strIngredient4": "Sugar",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 ",
      "strMeasure2": "1/2 can ",
      "strMeasure3": "1/2 ",
      "strMeasure4": "10 tsp ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-09-02 11:28:32"
    }
  ]
};

export const recipeInProgressAdam = {
  "cocktails": {
      "17837": [
        "Dark rum 2 oz ",
        "Lemon juice 1 oz "
      ]
  },
};

export const recipeInProgressBurek = {
  "meals": {
      "53060": [
        "Filo Pastry 1 Packet",
        "Minced Beef 150g",
        "Onion 150g"
      ]
  }
}

export const doneRecipeBurek = [
  {
    "id": "53060",
    "type": "food",
    "nationality": "Croatian",
    "category": "Side",
    "alcoholicOrNot": "",
    "name": "Burek",
    "image": "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
    "doneDate": "2/9/2022",
    "tags": [
      "Streetfood",
      " Onthego"
    ]
  }
]